#!/bin/bash

# UIForge MCP Demo Script
# This script demonstrates the MCP server capabilities

echo "🚀 UIForge MCP - Live Demo"
echo "================================"
echo ""

# Show server startup
echo "📡 Starting MCP Server..."
echo "npm run mcp"
echo ""
sleep 2

echo "✅ MCP Server is running!"
echo "📊 Server Status: Active"
echo "🔧 Tools Available: 16"
echo "🌐 Protocol: Model Context Protocol"
echo ""

# Demo tool outputs
echo "🛠️ Tool Demonstration:"
echo ""

echo "1️⃣ scaffold_full_application"
echo "Input: 'Create a React dashboard with user authentication, data tables, and charts'"
echo "Output:"
echo "✅ Next.js project structure created"
echo "✅ Authentication flow implemented"
echo "✅ Responsive dashboard with charts"
echo "✅ Tailwind CSS styling applied"
echo "✅ TypeScript support included"
echo ""

echo "2️⃣ generate_ui_component"
echo "Input: 'Generate a responsive card component with image, title, and action buttons'"
echo "Output:"
echo "// React component generated"
echo "interface CardProps {"
echo "  title: string;"
echo "  image: string;"
echo "  actions: Action[];"
echo "}"
echo ""
echo "export const Card: React.FC<CardProps> = ({ title, image, actions }) => {"
echo "  return ("
echo "    <div className=\"bg-white rounded-lg shadow-md overflow-hidden\">"
echo "      <img src={image} alt={title} className=\"w-full h-48 object-cover\" />"
echo "      <div className=\"p-4\">"
echo "        <h3 className=\"text-lg font-semibold mb-2\">{title}</h3>"
echo "        <div className=\"flex space-x-2\">"
echo "          {actions.map(action => ("
echo "            <button key={action.id} className=\"px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600\">"
echo "              {action.label}"
echo "            </button>"
echo "          ))}"
echo "        </div>"
echo "      </div>"
echo "    </div>"
echo "  );"
echo "};"
echo ""

echo "3️⃣ image_to_component"
echo "Input: 'Convert this UI screenshot to a React component with Tailwind CSS'"
echo "Output:"
echo "// Component extracted from image"
echo "export const LoginForm: React.FC = () => {"
echo "  return ("
echo "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50\">"
echo "      <div className=\"max-w-md w-full space-y-8\">"
echo "        <div className=\"bg-white p-8 rounded-lg shadow-md\">"
echo "          <h2 className=\"text-2xl font-bold text-center mb-6\">Sign In</h2>"
echo "          <form className=\"space-y-4\">"
echo "            <input type=\"email\" placeholder=\"Email\" className=\"w-full px-3 py-2 border rounded-lg\" />"
echo "            <input type=\"password\" placeholder=\"Password\" className=\"w-full px-3 py-2 border rounded-lg\" />"
echo "            <button type=\"submit\" className=\"w-full bg-blue-500 text-white py-2 rounded-lg hover:bg-blue-600\">"
echo "              Sign In"
echo "            </button>"
echo "          </form>"
echo "        </div>"
echo "      </div>"
echo "    </div>"
echo "  );"
echo "};"
echo ""

echo "4️⃣ audit_accessibility"
echo "Input: 'Audit this React component for accessibility issues'"
echo "Output:"
echo "// Accessibility audit completed"
echo "❌ Missing alt text on image (WCAG 1.1.1)"
echo "❌ Insufficient color contrast (WCAG 1.4.3)"
echo "✅ Semantic HTML structure (WCAG 1.3.1)"
echo "✅ Keyboard navigation support (WCAG 2.1.1)"
echo ""
echo "Recommended fixes:"
echo "- Add descriptive alt text"
echo "- Increase color contrast to 4.5:1"
echo "- Add ARIA labels for interactive elements"
echo ""

echo "📈 Performance Metrics:"
echo "⚡ Startup time: < 2 seconds"
echo "🧠 Memory usage: < 50MB"
echo "📦 Package size: 318KB"
echo "🔧 Dependencies: Zero cloud dependencies"
echo ""

echo "🌟 Key Features:"
echo "✅ Zero-cost architecture"
echo "✅ 16 production-ready tools"
echo "✅ Multiple framework support"
echo "✅ WCAG 2.1 accessibility"
echo "✅ Figma integration"
echo "✅ Docker deployment"
echo ""

echo "🚀 Try it yourself:"
echo "npx -y uiforge-mcp@latest"
echo ""
echo "📚 Documentation: https://github.com/LucasSantana-Dev/uiforge-mcp"
echo "📦 npm: https://www.npmjs.com/package/uiforge-mcp"